default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_development_db
  username: your_dev_db_user
  password: your_dev_db_password
  host: localhost

test:
  <<: *default
  database: your_test_db
  username: your_test_db_user
  password: your_test_db_password
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
